version: 2
updates:
  # 更新npm依赖和开发依赖
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "yearly"
    commit-message:
      prefix: "chore" # 可改为"deps"或其它自定义前缀
      prefix-development: "chore(dev)" # 用于开发依赖的提交前缀
    rebase-strategy: "auto" # 自动rebase来解决冲突
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch" # 忽略补丁版本更新
